apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jy3m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jy3m
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jy3m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jy3m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jy3m
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lmoq-tenant/rhtap-demo-app/hacbs-test-project-jy3m@sha256:b7f1ac0995c42408a033e78f19149a1075e54ac5649c1c6697f796a94a75bcde
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
